all:
	pdflatex -output-directory=out src/StatsHomework6.tex
	pdflatex -output-directory=out src/StatsHomework6.tex
	#pdflatex -output-directory=out src/Lab4.tex
	#pdflatex -output-directory=out src/Lab4.tex

	rm out/*.log out/*.aux out/*.toc
	mv out/StatsHomework6.pdf out/FOSTER_Hwk6.pdf
	#mv out/Lab4.pdf out/FOSTER_Lab4.pdf
	open out/FOSTER_Hwk6.pdf