all:
	pdflatex -output-directory=out src/StatsHomework4.tex
	pdflatex -output-directory=out src/StatsHomework4.tex
	pdflatex -output-directory=out src/Lab4.tex
	pdflatex -output-directory=out src/Lab4.tex

	rm out/*.log out/*.aux out/*.toc
	mv out/StatsHomework4.pdf out/FOSTER_Hwk4.pdf
	mv out/Lab4.pdf out/FOSTER_Lab4.pdf