all:
	pdflatex -output-directory=out src/StatsHomework7.tex
	pdflatex -output-directory=out src/StatsHomework7.tex
	#pdflatex -output-directory=out src/Lab4.tex
	#pdflatex -output-directory=out src/Lab4.tex

	rm out/*.log out/*.aux out/*.toc
	mv out/StatsHomework7.pdf out/FOSTER_Hwk7.pdf
	#mv out/Lab4.pdf out/FOSTER_Lab4.pdf
	open out/FOSTER_Hwk7.pdf