all:
	pdflatex -output-directory=out src/StatsHomework5.tex
	pdflatex -output-directory=out src/StatsHomework5.tex
	pdflatex -output-directory=out src/Lab5.tex
	pdflatex -output-directory=out src/Lab5.tex

	rm out/*.log out/*.aux out/*.toc
	mv out/StatsHomework5.pdf out/FOSTER_Hwk5.pdf
	mv out/Lab5.pdf out/FOSTER_Lab5.pdf