all:
	pdflatex -output-directory=out src/StatsHomework3.tex
	pdflatex -output-directory=out src/StatsHomework3.tex
	pdflatex -output-directory=out src/Lab3.tex
	pdflatex -output-directory=out src/Lab3.tex

	rm out/*.log out/*.aux out/*.toc
	mv out/StatsHomework3.pdf out/FOSTER_Hwk3.pdf
	mv out/Lab3.pdf out/FOSTER_Lab3.pdf